name: trading-platform
services:
  - name: backend
    project: ./backend
    host: appservice
    language: node
    platform: linux
    env:
      - name: MONGODB_URI
        value: ${MONGODB_URI}
      - name: JWT_SECRET
        value: ${JWT_SECRET}
      - name: PORT
        value: 8080
      - name: CORS_ORIGIN
        value: https://zippy-fudge-c2e7d7.netlify.app
      - name: NODE_ENV
        value: production